import { Global, Module } from '@nestjs/common';
import { MongooseModule, Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Types } from 'mongoose';

export enum Role {
  ADMIN = 'ADMIN',
  USER = 'USER',
}

@Schema({ timestamps: true, collection: 'user' })
export class UserModel {
  _id: Types.ObjectId; // auto generated by mongodb

  @Prop({ type: String, required: true })
  firstName: string;

  @Prop({ type: String, required: true })
  lastName: string;

  @Prop({ type: String, required: true, unique: true })
  email: string;

  @Prop({ type: String, required: true })
  passwordHash: string;

  @Prop({ type: String, required: true })
  dob: string;

  @Prop({ type: String, required: true })
  phoneNumber: string;

  @Prop({ type: Boolean, default: false })
  verified: boolean;

  @Prop({ type: Boolean, default: true })
  active: boolean;

  @Prop({ type: String, enum: Object.values(Role), default: Role.USER })
  role: Role;

  createdAt: Date; // auto generated as timestamps: true

  updatedAt: Date; // auto generated as timestamps: true
}

const UserSchema = SchemaFactory.createForClass(UserModel);

@Global()
@Module({
  imports: [MongooseModule.forFeature([{ name: UserModel.name, schema: UserSchema }])],
  exports: [MongooseModule],
})
export class UserModelModule {}
